#!/bin/sh 
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

{
	nohup aria2c --enable-rpc --rpc-listen-all
}&
sudo umount /dev/sda1
sudo mount /dev/sda1 -o uid-pi,gid-pi  /home/pi/ntfs
sudo umount /dev/sdb1
sudo mount /dev/sdb1 -o uid-pi,gid-pi  /home/pi/ntfs2
exit 0
